### ISSUE TITLE
Any chance to make it work with libraries that do not use jest assertions?

### ISSUE THREAD

**Issue by ivan-aksamentov** [ballercat/jest-plugin-must-assert#10]
Thanks for the great plugin!

My favourite redux-saga testing library, [`redux-saga-test-plan`](https://github.com/jfairbank/redux-saga-test-plan) 

It seems to be not using the assertions expected by `jest-plugin-must-assert`, but just `throw`s in case of error.

Any chance to make these two work together?

**Comment by ballercat** [comment]
Hi there!

Do you mean that the plugin will complain that no assertions were executed because of the `hasAssertions()` check which is done through the Jest built in API? 

Realistically best I could do here is expose an option which can turn off the `hasAssertion` logic. My worry is that it would be tough to emulate for a random library since it relies on some magical Jest internals (which would be next to impossible to emulate) . You would still get the benefit of renegade async event warnings.
