### ISSUE TITLE
Warnings when using supertest

### ISSUE THREAD

**Issue by ivan-aksamentov** [ballercat/jest-plugin-must-assert#11]
Despite node tests succeed, I receive the following warnings for every test involving [`supertest`](https://github.com/visionmedia/supertest):

> Test "\<test-name\>" is attempting to invoke a eventTask(Socket.addListener:close) after test completion. See stack-trace for details.

Example test:

```
  import request from 'supertest'

  ...

  it('replies with 200/success on valid request', async () => {
    const response = await request(app)
      .get(ENDPOINT)
      .send()

    expect(response.status).toBe(200)
    expect(response.body).toMatchObject({
      payload: {
          blaBla
      },
    })
  })

```

What do I do in order to fix this?

**Comment by bompus** [comment]
I'm getting the same error working with axios. I was able to workaround it by adding an await delay of 1ms (bouncing off the event loop?) at the end of the affected tests, but we all know how hacky that is.

**Comment by ballercat** [comment]
Hi @bompus. Any chance you could provide a minimal example of your test with axios?

**Comment by bompus** [comment]
@ballercat 

```
it('should have listening worker', async () => {
   expect.assertions(2);
   const res = await axios.request({ url: 'http://127.0.0.1:20000/dashboard/api/core/health/' });
   expect(res.status).toBe(200);
   expect(res.data.health).toBe('ok');
   // the following line has to be uncommented to avoid the eventTask warning
   // await new Promise(resolve => setTimeout(resolve, 10));
});
```

**Comment by ballercat** [comment]
Cool. So I was able to reproduce the warning. I don't think there is much to do on the library side, any particular bug to fix. It appears that the eventTask for the socket close event is fired after the test completes as described by the warning.

What I recommend is ignoring the socket close eventTask/letting it fire with the following snippet

```js
// <rootDir>/must-assert-setup.js
const patchJestAPI = require('jest-plugin-must-assert/manual');

patchJestAPI({
  onInvokeTask({
    originZoneId,
    currentZoneId,
    testName,
    taskType,
    taskSource,
  }) {
    // Don't block socket close events!
    if (taskType === 'eventTask' && taskSource === 'Socket.addListener:close') {
     return true;
    }

    // This is the default implementation of onInvokeTask. The error thrown will
    // be displayed as a logger.warn with a cleaned up stack trace.
    if (originZoneId !== currentZoneId) {
      throw new Error(
        `Test "${testName}" is attempting to invoke a ${taskType}(${taskSource}) after test completion. Ignoring`
      );
    }
    return true;
  }
}
```

then use it in your jest config instead of the out-of-the-box plugin

```
...
setupFilesAfterEnv: [
  '<rootDir>/must-assert-setup'
],
...
```

You'll be able to avoid the random timer in your tests this way as the event will be allowed to fire. 

I may add this to the README since it does seem like something that might happen to more folks. Thanks!
